runs:
  using: "composite"
  steps:
    - name: CodeAnalysis via  detekt
      shell: bash
      run: ./gradlew detekt

    - name: Upload detekt results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: detekt_results
        path:  |
          app/build/reports/detekt
          dog_network/build/reports/detekt

    - name: Set Output
      if: always()
      uses: actions/github-script@v3 #todo pass fail cancelled ke alag alag status
      with:
        script: |
          core.setOutput('slack_msg', 'detekt: 🔜');
