runs:
  using: "composite"
  steps:
    - name: CodeAnalysis via  detekt
      run: ./gradlew detekt

    - name: Upload detekt results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: detekt_results
        path:  |
          app/build/reports/detekt
          dog_network/build/reports/detekt
#