runs:
  using: "composite"
  steps:
    - name: Check if Skip
      if: ${{env.SKIP_CODE_CHECKS}}
      shell: bash
      run: echo "This step will be skipped"

    - name: CodeAnalysis via  detekt
      if: ${{!env.SKIP_CODE_CHECKS}}
      shell: bash
      run: ./gradlew detekt

    - name: Upload detekt results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: detekt_results
        path:  |
          app/build/reports/detekt
          dog_network/build/reports/detekt
