name: android-master

on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Start Lint Check
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: lint

      - name: Upload Lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint_results
          path: app/build/reports/lint-results-debug.html

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Start Unit Tests
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: test

      - name: Upload Unit tests results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html

  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk