runs:
  using: "composite"
  steps:
    - name: Release on Github.
      run:  echo "hello"
#      uses: "marvinpinto/action-automatic-releases@latest"
#      with:
#        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#        draft: true
#        prerelease: false
#        automatic_release_tag: ${{ github.event.inputs.tag_name }}
#        title: ${{ github.event.inputs.title }}
#        files: |
#          dog_network/build/outputs/aar
