runs:
  using: "composite"
  steps:
    - name: Check lint
      shell: bash
      run: ./gradlew lint

    - name: Upload Lint results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: lint_results
        path:  |
          app/build/reports/lint-results-debug.html
          dog_network/build/reports/lint-results-debug.html

    - name: Set Output
      if: always()
      uses: actions/github-script@v3 #todo pass fail cancelled ke alag alag status
      shell: bash
      run: |
        echo "slack_msg=Check lint : 🔜" >> $GITHUB_ENV

