runs:
  using: "composite"
  steps:
    - name: Run Unit Tests And Code Coverage
      shell: bash
      run: ./gradlew jacocoTestReportDebug jacocoTestReportRelease

    - name: Upload Unit tests
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: unit-tests-results.zip
        path: |
          app/build/reports/tests
          app/build/reports/jacoco

          dog_network/build/reports/tests
          dog_network/build/reports/jacoco

    - name: Set Output
      if: always()
      uses: actions/github-script@v3 #todo pass fail cancelled ke alag alag status
      shell: bash
      run: |
        echo "slack_msg=tests and coverage: 🔜" >> $GITHUB_ENV
