runs:
  using: "composite"
  steps:
    - name: app>> Run Unit Tests And Code Coverage
      shell: bash
      run: ./gradlew :app:jacocoTestReportDebug :app:jacocoTestReportRelease

    - name: app>> Upload Unit tests Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: app_unit_test
        path: app/build/reports/tests

    - name: app>> Upload Code Coverage Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: app_coverage
        path:  app/build/reports/jacoco

    - name: dog_network>> Run Unit Tests And Code Coverage
      shell: bash
      run: ./gradlew :dog_network:jacocoTestReportDebug :dog_network:jacocoTestReportRelease

    - name: dog_network>> Upload Unit tests Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: dog_network_unit_test
        path: dog_network/build/reports/tests

    - name: dog_network>> Upload Code Coverage Report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: dog_network_coverage
        path:  dog_network/build/reports/jacoco

