runs:
  using: "composite"
  steps:
    - name: Generate AAR and APK files
      shell: bash
      run: ./gradlew assembleDebug

    - name: Upload AAR and apk files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: aars_and_apks.zip
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          dog_network/build/outputs/aar

#    - name: Set Output
#      if: always()
#      shell: bash
#      run: echo "slack_msg=build code--🔜" >> $GITHUB_ENV
