runs:
  using: "composite"
  steps:
    - name: Generate AAR and APK files
      if: success()
      shell: bash
      run: ./gradlew assembleDebug

    - name: Upload AAR files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: unit-tests-results.zip
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          dog_network/build/outputs/aar
