inputs:
  SLACK_WEBHOOK_URL:
    required: false  #todo make madatory
  LAST_RUN_TASK:
    required: false #todo make madatory

runs:
  using: "composite"
  steps:
    - name: setColor if failure
      if: ${{ job.status=='failure' }}
      shell: bash
      run: |
        echo "STATUS_COLOR=#fc0703" >> $GITHUB_ENV
        echo "STATUS_EMOJI=💔" >> $GITHUB_ENV

    - name: setColor if success
      if: ${{ job.status=='success' }}
      shell: bash
      run: |
        echo "STATUS_COLOR=#00c247" >> $GITHUB_ENV
        echo "STATUS_EMOJI=💚" >> $GITHUB_ENV

    - name: setColor if cancelled
      if: ${{ job.status=='cancelled'}}
      shell: bash
      run: |
        echo "STATUS_COLOR=#fc9003" >> $GITHUB_ENV
        echo "STATUS_EMOJI=✖️" >> $GITHUB_ENV

    - name: Send custom JSON data to Slack workflow.
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "attachments": [
              {
                "color": "${{env.STATUS_COLOR}}",
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*GitHub Action build results*  ℹ️️"
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "• ${{inputs.LAST_RUN_TASK}} - ${{ job.status }} ${{env.STATUS_EMOJI}}"
                    }
                  },
                  {
                    "type": "divider"
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "• commit info :  <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{github.event.head_commit.message}}>"
                    }
                  },

                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "• Full Runner URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'"
                    }
                  }

                ]
              }
            ]
          }
