runs:
  using: "composite"
  steps:
#    - name: Publish to MavenCentral
#      if: ${{ contains(github.event.head_commit.message, '[UPLOAD]') }}
#      shell: bash
#      run: ./gradlew publishToSonatype --max-workers 1 closeAndReleaseSonatypeStagingRepository
#      env:
#        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
#        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
#        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

    - name: Set Output
      if: always()
      uses: actions/github-script@v3 #todo pass fail cancelled ke alag alag status
      with:
        script: |
          core.setOutput('slack_msg', 'maven central release: 🔜');

