runs:
  using: "composite"
  steps:
    - name: CodeAnalysis via  checkstyle
      shell: bash
      run: ./gradlew checkstyle

    - name: Upload checkstyle results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle_results
        path: |
          app/build/reports/checkstyle
          dog_network/build/reports/checkstyle

    - name: Set Output
      if: always()
      uses: actions/github-script@v3 #todo pass fail cancelled ke alag alag status
      shell: bash
      run: |
        echo "slack_msg=checkstyle: 🔜" >> $GITHUB_ENV
