runs:
  using: "composite"
  steps:
    - name: Check if Skip
      if: ${{env.SKIP_CODE_CHECKS}}
      shell: bash
      run: echo "This step will be skipped"

    - name: CodeAnalysis via  checkstyle
      if: ${{!env.SKIP_CODE_CHECKS}}
      shell: bash
      run: ./gradlew checkstyle

    - name: Upload checkstyle results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: checkstyle_results
        path: |
          app/build/reports/checkstyle
          dog_network/build/reports/checkstyle
