name: run junit tests

#---------------------------------------------------------------------------------------------------------------------
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: test

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build
