name: CI/CD develop
on:
  push:
    branches: [ develop ]

jobs:
  basic_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions.
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
        
      - name: CodeAnalysis via detekt
        run: ./gradlew detekt

      - name: Upload detekt results
        uses: actions/upload-artifact@v2
        with:
          name: detekt_results
          path: app/build/reports/detekt

      - name: CodeAnalysis via checkstyle
        run: ./gradlew checkstyle

      - name: Upload checkstyle results
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-results
          path: app/build/reports/checkstyle
      
      - name: Check lint
        if: always()
        run: ./gradlew lint

      - name: Run Unit Tests
        if: always()
        # run: ./gradlew testDebugUnitTest
        run: ./gradlew jacocoTestReportDebug

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Unit tests
        id: tests
        run: ./gradlew test

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.COOLTOOL_SIGNING_KEY }}
          alias: ${{ secrets.COOLTOOL_ALIAS }}
          keyStorePassword: ${{ secrets.COOLTOOL_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.COOLTOOL_KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v2
        with:
            name: app
            path: app/build/outputs/bundle/release/app-release.aab

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.FURRYPAL_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store (ALPHA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: work.curioustools.dogfinder
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: alpha
          whatsNewDirectory: distribution/whatsnew

          
      # - name: Generate AAR and APK files
      #   if: always()
      #   run: ./gradlew assembleDebug

      # - name: Upload AAR files
      #   if: always()
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: artifacts.zip
      #     path: |
      #       app/build/outputs/apk/debug/app-debug.apk
      #       dog_network/build/outputs/aar
          
