name: manually create a release to github releases # works only after being pushed to master
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'enter a tag name:'
        required: true
        type: string

      title:
        description: 'enter a release title:'
        required: true
        type: string


#      environment:
#        description: 'Environment to run tests against'
#        type: environment
#        required: true
#      logLevel:
#        description: 'Log level for workflow:'
#        required: true
#        default: 'warning'
#        type: choice
#        options:
#          - info
#          - warning
#          - debug
#        tags:
#          description: 'Test scenario tags'
#          required: false
#          type: boolean


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: "create release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: true
          automatic_release_tag: ${{ github.event.inputs.tag_name }}
          title: ${{ github.event.inputs.title }}

