name: manually create a release to github releases # works only after being pushed to master
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level for workflow:'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      tag_name:
        description: 'enter a tag name'
        required: true
        type: string

      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello ji , tag hai ye: ${{ github.event.inputs.tag_name }}"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
          echo "tag:  $TAG_NAME"