name: manual_g_release.yml >> manually create a release to github releases # works only after being pushed to master
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'enter a tag name:'
        required: true
        type: string

      title:
        description: 'enter a release title:'
        required: true
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Actions.
        uses: actions/checkout@v2

      - name: Set up JDK 11.
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Generate AAR and APK files.
        run: ./gradlew assembleDebug

      - name: Release on Github.
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          automatic_release_tag: ${{ github.event.inputs.tag_name }}
          title: ${{ github.event.inputs.title }}
          files: |
            dog_network/build/outputs/aar