name: task - validate commit on master
on:
  push:
    branches: [ master ]

jobs:
  lint_test_build_assemble:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2


      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Check lint via marketplace gradle action (similar to gradle command `./gradlew lint`)
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: lint

      - name: Upload Lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint_results
          path: app/build/reports/lint-results-debug.html

      - name: Run Tests ( marketplace gradle action similar to gradle command `./gradlew test`)
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: test

      - name: Upload Unit tests
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html


      - name: Build code ( marketplace gradle action similar to gradle command `./gradlew build`)
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: build

      - name: Generate apk ( marketplace gradle action similar to gradle command `./gradlew assembleDebug`)
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: assembleDebug

      - name: Upload APK via marketplace  action
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

