name: task - validate commit on master
on:
  push:
    branches: [ master ]

jobs:
  lint-staticChecks-test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions
        uses: actions/checkout@v2

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack

      - name: Mandaory File Changes
        uses: ./.github/mini_flows/s1_mandatory_filechanges


      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack

      - name: Setup JDK 11.
        uses: ./.github/mini_flows/s2_setup_jdk

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack


      - name: Run lint tests and Upload results
        uses: ./.github/mini_flows/s3_lint

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack


      - name: Static Code Check Via detekt
        uses: ./.github/mini_flows/s4_detekt

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack


      - name: Static Code Check Via checkstyle
        uses: ./.github/mini_flows/s5_checkstyle

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack


      - name: Unit Tests and Jacoco Coverage (DEBUG AND RELEASE)
        uses: ./.github/mini_flows/s6_test_coverage

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack


      - name: Build Code
        uses: ./.github/mini_flows/s7_build

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack


      - name: Release to maven central
        uses: ./.github/mini_flows/s8_maven_release

      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack


      - name: Relase to github
        uses: ./.github/mini_flows/s9_git_release


      - name: Slack Status Notification
        if: always()
        uses: ./.github/mini_flows/ss1_slack








# this type of integration is also cool : https://github.com/voxmedia/github-action-slack-notify-build
#https://raw.githubusercontent.com/voxmedia/github-action-slack-notify-build/main/docs/updating_message.gif
# this slack , hosted by anshsachdeva2013 : https://app.slack.com/client/T037QDTAE9M/C03825HTMJ9